[package]
name = "musl"
version = "1.2.6"
description = "C standard library"
deps = [] # should be skeleton and other stuff but this is a test
# arch = ["x86_64"] - this works with any arch (i think?) given the right compiler so does not apply
keywords = ["libc", "musl", "embedded"]

[maintainers]
EclipseLinux = "Eclipse Linux"
chkc0x0 = "Chkc"

[meta]
upstream = "https://musl.libc.org/"
# homepage - same as upstream if not specified
license = "MIT" # can be an array too
author = ["Rich Felker <gh:richfelker>", "musl contributors"]

[build]
# *here* is the actual source
url = "git://git.musl-libc.org/musl"
# sha256 = ""
rev = "b306b16af15c89a04d8e0c55cac2dadbeb39c083" # as of july 25
type = "make"
deps = ["gcc", "binutils", "bash"]
post = ["ln -s /usr/lib/libc.so /usr/lib/ld-musl-$ARCH.so.1"]

[install]
pre = [""]
post = [""]

# reconstruction using r2 data
[source.x86_64]
sha = "f42bbb40a71c0da0f15350d0277171423519766e08daf5580a1c2c753c4d9366"
rev = 2
commit = "b306b16"
timestamp = 1789072603
compressed = 719610
uncompressed = 4089113
